"""GitHub API write tools used exclusively by the Coordinator agent."""

from __future__ import annotations

import json
import os
import re
from datetime import date

from agent.config import SeccureState
from agent.tools.github_client import get, patch, post

ATTEMPT_MARKER = "<!-- seccure-attempt-count:"
_ATTEMPT_RE = re.compile(r"<!--\s*seccure-attempt-count:(\d+)\s*-->")


def _repo() -> str:
    return os.environ["TARGET_REPO"]


# ---------------------------------------------------------------------------
# Idempotency guard
# ---------------------------------------------------------------------------


def check_existing_seccure_pr() -> str:
    """Check whether an open PR with the 'seccure' label already exists.

    Returns:
        JSON string with: found, pr_number, url, body, and attempt_count.
    """
    repo = _repo()
    prs = get(f"/repos/{repo}/pulls", state="open", per_page=100)
    if not isinstance(prs, list):
        return json.dumps({"found": False, "pr_number": None, "url": None})

    for pr in prs:
        labels = [lb["name"] for lb in pr.get("labels", [])]
        if "seccure" in labels:
            return json.dumps(
                {
                    "found": True,
                    "pr_number": pr["number"],
                    "url": pr["html_url"],
                    "body": pr.get("body") or "",
                    "attempt_count": extract_attempt_count(pr.get("body") or ""),
                }
            )

    return json.dumps(
        {"found": False, "pr_number": None, "url": None, "body": "", "attempt_count": 0}
    )


def extract_attempt_count(body: str) -> int:
    """Read the persisted Seccure retry count from a PR body marker."""

    match = _ATTEMPT_RE.search(body or "")
    return int(match.group(1)) if match else 0


def with_attempt_marker(body: str, attempt_count: int) -> str:
    """Attach or replace the hidden retry marker."""

    marker = f"<!-- seccure-attempt-count:{attempt_count} -->"
    if _ATTEMPT_RE.search(body):
        return _ATTEMPT_RE.sub(marker, body)
    return f"{body.rstrip()}\n\n{marker}\n"


def render_pr_title_body(state: SeccureState) -> tuple[str, str]:
    """Render deterministic Seccure PR title/body from typed state."""

    fixed_rows = []
    for result in state.fix_results:
        if not result.fixed:
            continue
        row_template = (
            "| {package} | {from_version} | {to_version} | "
            "{strategy} | {cve} | {severity} |"
        )
        fixed_rows.append(
            row_template.format(
                package=result.package,
                from_version=result.from_version,
                to_version=result.to_version or "",
                strategy=result.strategy,
                cve=result.cve_id or "",
                severity=result.severity or "",
            )
        )
    if not fixed_rows:
        fixed_rows.append("| _No package changes_ |  |  |  |  |  |")

    conflict_lines = []
    for issue_number in state.conflict_issue_numbers:
        conflict_lines.append(f"- #{issue_number}")

    pr_closes = []
    for pr in state.dependabot_prs:
        pr_number = getattr(pr, "pr_number", None)
        if pr_number:
            pr_closes.append(f"- Closes #{pr_number}")
    if not pr_closes:
        pr_closes.append("- None")

    issue_closes = [
        f"- Closes #{issue.issue_number}" for issue in state.security_issues
    ]
    if not issue_closes:
        issue_closes.append("- None")

    title = "fix(deps): automated Seccure security updates"
    body = f"""## Seccure Automated Security Patch

Auto-generated by the Seccure Agent.

### Packages Fixed
| Package | From | To | Strategy | CVE | Severity |
|---------|------|----|----------|-----|----------|
{chr(10).join(fixed_rows)}
"""

    if conflict_lines:
        body += "\n### Could Not Auto-Fix\n" + "\n".join(conflict_lines) + "\n"

    body += f"""
### Closes Dependabot PRs
{chr(10).join(pr_closes)}

### Closes Issues
{chr(10).join(issue_closes)}

---
PRs created by GITHUB_TOKEN may not trigger CI workflows automatically.
"""
    return title, with_attempt_marker(body, state.attempt_count)


def close_seccure_pr(pr_number: int) -> str:
    """Close an existing Seccure PR with an explanatory comment.

    Args:
        pr_number: The pull request number to close.

    Returns:
        Confirmation message.
    """
    repo = _repo()
    post(
        f"/repos/{repo}/issues/{pr_number}/comments",
        {
            "body": (
                "🔄 **Seccure Agent** is re-running and has superseded this PR.\n\n"
                "A fresh, up-to-date fix PR will be opened shortly."
            )
        },
    )
    patch(f"/repos/{repo}/pulls/{pr_number}", {"state": "closed"})
    return f"Closed existing Seccure PR #{pr_number}."


# ---------------------------------------------------------------------------
# Repository metadata
# ---------------------------------------------------------------------------


def get_default_branch() -> str:
    """Get the default branch name of the target repository.

    Returns:
        The default branch name (e.g. 'main' or 'master').
    """
    data = get(f"/repos/{_repo()}")
    return str(data.get("default_branch", "main"))


# ---------------------------------------------------------------------------
# PR creation
# ---------------------------------------------------------------------------


def create_pull_request(
    title: str,
    body: str,
    head_branch: str,
    base_branch: str,
) -> str:
    """Create the consolidated security fix pull request.

    Args:
        title: The PR title.
        body: Full markdown PR body. Must contain Closes #N references.
        head_branch: The fix branch to merge from.
        base_branch: The target base branch (default branch).

    Returns:
        JSON string with: pr_number, url.
    """
    data = post(
        f"/repos/{_repo()}/pulls",
        {"title": title, "body": body, "head": head_branch, "base": base_branch},
    )
    return json.dumps({"pr_number": data["number"], "url": data["html_url"]})


def update_pull_request(pr_number: int, title: str, body: str) -> str:
    """Update an existing pull request.

    Args:
        pr_number: The pull request number to update.
        title: The new PR title.
        body: The new full markdown PR body. Must contain Closes #N references.

    Returns:
        JSON string with: pr_number, url.
    """
    data = patch(
        f"/repos/{_repo()}/pulls/{pr_number}",
        {"title": title, "body": body},
    )
    return json.dumps({"pr_number": data["number"], "url": data["html_url"]})


def upsert_seccure_pr(
    state_json: str,
    head_branch: str,
    base_branch: str,
    existing_pr_number: int | None = None,
) -> str:
    """Create or update the single consolidated Seccure PR."""

    state = SeccureState.model_validate_json(state_json)
    title, body = render_pr_title_body(state)
    if existing_pr_number:
        result = update_pull_request(existing_pr_number, title, body)
    else:
        result = create_pull_request(title, body, head_branch, base_branch)
    data = json.loads(result)
    add_labels(data["pr_number"], ["seccure", "auto-fix", "dependabot"])
    return result


def add_labels(pr_number: int, labels: list[str]) -> str:
    """Add labels to a pull request or issue.

    Args:
        pr_number: The PR or issue number.
        labels: List of label name strings to add.

    Returns:
        Confirmation message.
    """
    post(f"/repos/{_repo()}/issues/{pr_number}/labels", {"labels": labels})
    return f"Labels {labels} added to #{pr_number}."


# ---------------------------------------------------------------------------
# Conflict issue creation
# ---------------------------------------------------------------------------


def create_conflict_issue(
    package: str,
    cve_id: str,
    severity: str,
    advisory_url: str,
    reason: str,
) -> str:
    """Create a GitHub issue for a vulnerability that could not be auto-fixed.

    Args:
        package: The npm package name.
        cve_id: The CVE or GHSA identifier.
        severity: Severity level (low/medium/high/critical).
        advisory_url: URL to the security advisory.
        reason: Human-readable explanation of why the fix failed.

    Returns:
        JSON string with: issue_number, url.
    """
    today = date.today().isoformat()
    body = f"""## 🚨 Unresolved Vulnerability: `{package}`

Seccure Agent attempted all fix strategies and failed.

| Field | Value |
|-------|-------|
| Package | `{package}` |
| CVE | [{cve_id}]({advisory_url}) |
| Severity | `{severity}` |
| Strategies tried | npm audit fix, npm overrides, manual bump |
| Reason | {reason} |

### Recommended Manual Action
1. Run `npm ls {package}` to trace the dependency chain
2. Check if a major version upgrade of the parent dependency resolves this
3. Consider replacing the dependency if no fix is available

---
> Created by Seccure Agent on {today}.
"""
    data = post(
        f"/repos/{_repo()}/issues",
        {
            "title": f"🚨 Unresolved vulnerability: {package} ({cve_id})",
            "body": body,
            "labels": ["security", "conflict", "seccure"],
        },
    )
    return json.dumps({"issue_number": data["number"], "url": data["html_url"]})
