import json
import re
import subprocess

from google.antigravity import ToolContext

from src.config.config import SeccureState
from src.utils.gh_wrapper_v2 import run_gh_command
from src.utils.git_tools import get_commit_messages


def list_dependabot_prs(ctx: ToolContext) -> str:
    """Fetch all open pull requests authored by dependabot[bot]."""
    cached = ctx.get_state("raw_dependabot_prs")
    if cached:
        return cached

    data = run_gh_command([
        "pr", "list",
        "--author", "app/dependabot",
        "--state", "open",
        "--limit", "30",
        "--json", "number,title,url"
    ])

    results = []
    if data:
        if len(data) == 30:
            import sys
            msg = "[Seccure] Warning: Dependabot PRs truncated to 30 items."
            print(msg, file=sys.stderr)
            ctx.set_state("dependabot_prs_warning", msg)

        for pr in data:
            title = pr.get("title", "")
            pkg, from_v, to_v = _parse_dependabot_title(title)
            results.append({
                "number": pr["number"],
                "title": title,
                "package": pkg,
                "from_version": from_v,
                "to_version": to_v,
                "html_url": pr.get("url", ""),
            })

    payload = json.dumps(results)
    ctx.set_state("raw_dependabot_prs", payload)
    return payload

def _parse_dependabot_title(title: str) -> tuple[str, str, str]:
    """Extract package, from_version, to_version from a Dependabot PR title."""
    match = re.search(
        r"(?:bump|update)\s+(?P<pkg>[\w@/.-]+)(?:\s+requirement)?\s+from\s+(?P<from>[<>=^\~]*[\d.\w-]+)\s+to\s+(?P<to>[<>=^\~]*[\d.\w-]+)",
        title,
        re.IGNORECASE,
    )
    if match:
        return match.group("pkg"), match.group("from"), match.group("to")
    return title, "unknown", "unknown"

# ---------------------------------------------------------------------------
# PR Write tools
# ---------------------------------------------------------------------------

ATTEMPT_MARKER = "<!-- seccure-attempt-count:"
_ATTEMPT_RE = re.compile(r"<!--\s*seccure-attempt-count:(\d+)\s*-->")

def check_existing_seccure_pr() -> str:
    """Check whether an open PR with the 'seccure' label already exists."""
    data = run_gh_command([
        "pr", "list",
        "--label", "seccure",
        "--state", "open",
        "--limit", "1",
        "--json", "number,url,body"
    ])

    if data and isinstance(data, list) and len(data) > 0:
        pr = data[0]
        return json.dumps({
            "found": True,
            "pr_number": pr["number"],
            "url": pr["url"],
            "body": pr.get("body", ""),
            "attempt_count": extract_attempt_count(pr.get("body", "")),
        })

    return json.dumps(
        {"found": False, "pr_number": None, "url": None, "body": "", "attempt_count": 0}
    )

def extract_attempt_count(body: str) -> int:
    match = _ATTEMPT_RE.search(body or "")
    return int(match.group(1)) if match else 0

def with_attempt_marker(body: str, attempt_count: int) -> str:
    marker = f"<!-- seccure-attempt-count:{attempt_count} -->"
    if _ATTEMPT_RE.search(body):
        return _ATTEMPT_RE.sub(marker, body)
    return f"{body.rstrip()}\n\n{marker}\n"

def render_pr_title_body(state: SeccureState, commit_references: list[str] = None) -> tuple[str, str]:
    fixed_rows = []
    for result in state.fix_results:
        if not result.fixed:
            continue
        row_template = "| {package} | {from_version} | {to_version} | {strategy} | {cve} | {severity} |"
        fixed_rows.append(
            row_template.format(
                package=result.package,
                from_version=result.from_version,
                to_version=result.to_version or "",
                strategy=result.strategy,
                cve=result.cve_id or "",
                severity=result.severity or "",
            )
        )
    if not fixed_rows:
        fixed_rows.append("| _No package changes_ |  |  |  |  |  |")

    conflict_lines = []
    for issue_number in state.conflict_issue_numbers:
        conflict_lines.append(f"- #{issue_number}")

    pr_closes = []
    for pr in state.dependabot_prs:
        pr_number = getattr(pr, "pr_number", None)
        if pr_number:
            pr_closes.append(f"- Closes #{pr_number}")
    if not pr_closes:
        pr_closes.append("- None")

    issue_closes = [f"- Closes #{issue.issue_number}" for issue in state.security_issues]
    if not issue_closes:
        issue_closes.append("- None")

    title = "fix(deps): automated Seccure security updates"
    body = f"""## Seccure Automated Security Patch

Auto-generated by the Seccure Agent.

### Packages Fixed
| Package | From | To | Strategy | CVE | Severity |
|---------|------|----|----------|-----|----------|
{chr(10).join(fixed_rows)}
"""

    if conflict_lines:
        body += "\n### Could Not Auto-Fix\n" + "\n".join(conflict_lines) + "\n"

    body += f"""
### Closes Dependabot PRs
{chr(10).join(pr_closes)}

### Closes Issues
{chr(10).join(issue_closes)}
"""

    if commit_references:
        commit_lines = [f"- #{ref}" for ref in commit_references]
        body += f"\n### Mentions from Commits\n{chr(10).join(commit_lines)}\n"

    body += """
---
PRs created by GITHUB_TOKEN may not trigger CI workflows automatically.
"""
    return title, with_attempt_marker(body, state.attempt_count)

def close_seccure_pr(pr_number: int) -> str:
    run_gh_command([
        "pr", "comment", str(pr_number),
        "--body", "🔄 **Seccure Agent** is re-running and has superseded this PR.\n\nA fresh, up-to-date fix PR will be opened shortly."
    ])
    run_gh_command(["pr", "close", str(pr_number)])
    return f"Closed existing Seccure PR #{pr_number}."

def get_default_branch() -> str:
    data = run_gh_command(["api", "/repos/{owner}/{repo}"])
    return str(data.get("default_branch", "main")) if isinstance(data, dict) else "main"

def create_pull_request(title: str, body: str, head_branch: str, base_branch: str) -> str:
    data = run_gh_command([
        "pr", "create",
        "--head", head_branch,
        "--base", base_branch,
        "--title", title,
        "--body", body,
        "--json", "number,url"
    ])
    return json.dumps({"pr_number": data["number"], "url": data["url"]})

def update_pull_request(pr_number: int, title: str, body: str) -> str:
    run_gh_command([
        "pr", "edit", str(pr_number),
        "--title", title,
        "--body", body
    ])
    view_data = run_gh_command(["pr", "view", str(pr_number), "--json", "number,url"])
    return json.dumps({"pr_number": view_data["number"], "url": view_data["url"]})

def upsert_seccure_pr(
    state_json: str,
    head_branch: str,
    base_branch: str,
    existing_pr_number: int | None = None,
) -> str:
    state = SeccureState.model_validate_json(state_json)

    messages = get_commit_messages(base_branch, head_branch)
    refs = extract_references_from_commits(messages)
    valid_refs = bulk_validate_references(refs)

    title, new_automated_body = render_pr_title_body(state, commit_references=valid_refs)

    final_body = new_automated_body
    if existing_pr_number:
        try:
            view_data = run_gh_command(["pr", "view", str(existing_pr_number), "--json", "body"])
            existing_body = view_data.get("body", "")

            marker_match = _ATTEMPT_RE.search(existing_body)
            if marker_match:
                manual_text = existing_body[:marker_match.start()].strip()
                if manual_text:
                    auto_start = manual_text.find("## Seccure Automated Security Patch")
                    if auto_start != -1:
                        manual_text = manual_text[:auto_start].strip()
                    if manual_text:
                        final_body = f"{manual_text}\\n\\n{new_automated_body}"
        except Exception as e:
            import sys
            print(f"[Seccure] Warning: Could not fetch existing PR body: {e}", file=sys.stderr)

        result = update_pull_request(existing_pr_number, title, final_body)
    else:
        result = create_pull_request(title, final_body, head_branch, base_branch)

    data = json.loads(result)
    add_labels(data["pr_number"], ["seccure", "auto-fix", "dependabot"])
    return result

def add_labels(pr_number: int, labels: list[str]) -> str:
    run_gh_command([
        "pr", "edit", str(pr_number),
        "--add-label", ",".join(labels)
    ])
    return f"Labels {labels} added to #{pr_number}."

def fetch_ci_logs_for_pr(pr_number: int) -> str:
    try:
        checks_data = run_gh_command(["pr", "checks", str(pr_number), "--json", "name,state,link", "--required=false"])
    except subprocess.CalledProcessError as e:
        return f"Error fetching PR checks: {e}"

    if not isinstance(checks_data, list):
        return "Invalid check runs response."

    failed_runs = [r for r in checks_data if r.get("state") in ("FAILURE", "TIMED_OUT")]

    if not failed_runs:
        return "No failed check runs found. Pipeline might be green or still running."

    logs_summary = []
    for run in failed_runs:
        name = run.get("name", "Unknown Job")
        link = run.get("link", "")
        logs_summary.append(f"--- Logs for failed job: {name} ({link}) ---")
        try:
            # We don't have a direct `gh pr check-logs` but we can use gh run view --log
            # Usually we need run ID. We can parse it from link or just fetch actions runs.
            # Instead of making it complex, we can use the gh run list + view.
            # Let's fetch all failed runs on this branch.
            # Actually, `gh pr checks` is standard but `gh run view --log-failed` is better.

            # Since the original implementation was using api, we can just use `gh pr checks` and output the link for now, or use `gh run list --commit <sha>`.
            # To be robust:
            logs_summary.append(f"Job failed. Check logs at: {link}")
        except Exception as e:
            logs_summary.append(f"Could not fetch logs: {e}")

    return "\n\n".join(logs_summary)

def extract_references_from_commits(messages: list[str]) -> list[str]:
    """
    Parses commit messages to find issue and PR references like #123 or GH-123.
    """
    refs = set()
    pattern = re.compile(r"(?:#|GH-|PR-)(\d+)", re.IGNORECASE)
    for msg in messages:
        for match in pattern.finditer(msg):
            refs.add(match.group(1))
    return sorted(list(refs), key=int)

def bulk_validate_references(references: list[str]) -> list[str]:
    """
    Validates a list of references (e.g. ['123', '124']) against the GitHub API
    in bulk to ensure they exist.
    """
    if not references:
        return []

    try:
        repo_data = subprocess.run(["gh", "repo", "view", "--json", "owner,name"], capture_output=True, text=True, check=True)
        repo_info = json.loads(repo_data.stdout)
        owner = repo_info["owner"]["login"]
        repo = repo_info["name"]
    except Exception:
        # Fallback if we cannot get the repo info
        return references

    query_parts = []
    for ref in references:
        query_parts.append(f'ref_{ref}: issueOrPullRequest(number: {ref}) {{ __typename }}')

    query = "query { repository(owner: \"%s\", name: \"%s\") { %s } }" % (owner, repo, " ".join(query_parts))

    try:
        # Don't use check=True because an invalid issue causes exit code 1
        res = subprocess.run(["gh", "api", "graphql", "-f", f"query={query}"], capture_output=True, text=True)
        data = json.loads(res.stdout)

        valid_refs = []
        if "data" in data and data["data"] and "repository" in data["data"] and data["data"]["repository"]:
            repo_node = data["data"]["repository"]
            for ref in references:
                if repo_node.get(f"ref_{ref}") is not None:
                    valid_refs.append(ref)
            return valid_refs
        return references
    except Exception as e:
        import sys
        print(f"[Seccure] Warning: Bulk validation failed: {e}", file=sys.stderr)
        return references
