import re

_ATTEMPT_RE = re.compile(r"<!--\s*seccure-attempt-count:(\d+)\s*-->")

existing_body = """This is my custom description.
Please review carefully.

## Seccure Automated Security Patch

Auto-generated by the Seccure Agent.

### Packages Fixed
| Package | From | To | Strategy | CVE | Severity |
|---------|------|----|----------|-----|----------|
| semver | 5.7.1 | 5.7.2 | fix | CVE-2022-25883 | high |

### Closes Dependabot PRs
- None

### Closes Issues
- None

---
PRs created by GITHUB_TOKEN may not trigger CI workflows automatically.

<!-- seccure-attempt-count:1 -->
"""

new_automated_body = """## Seccure Automated Security Patch

Auto-generated by the Seccure Agent.

### Packages Fixed
| Package | From | To | Strategy | CVE | Severity |
|---------|------|----|----------|-----|----------|
| semver | 5.7.1 | 5.7.2 | fix | CVE-2022-25883 | high |
| another | 1.0 | 2.0 | fix | | |

### Closes Dependabot PRs
- None

### Closes Issues
- None

---
PRs created by GITHUB_TOKEN may not trigger CI workflows automatically.

<!-- seccure-attempt-count:2 -->
"""

final_body = new_automated_body
marker_match = _ATTEMPT_RE.search(existing_body)
if marker_match:
    manual_text = existing_body[:marker_match.start()].strip()
    if manual_text:
        auto_start = manual_text.find("## Seccure Automated Security Patch")
        if auto_start != -1:
            manual_text = manual_text[:auto_start].strip()

        if manual_text:
            final_body = f"{manual_text}\n\n{new_automated_body}"

print("FINAL BODY:\n")
print(final_body)

